### ISSUE TITLE
Research a Tool to Use for Statistics

### ISSUE THREAD

**Issue by joandrews** [bcgov/agri-nmp#626]
**Describe the task**
User statistics for all three tools (NMP, ARM, MSA) in 2023 - such as number of users, city of use, time spent on page, etc. (really whatever is available)

**Purpose**
User statistics were typically acquired from Google Analytics, but connection to the tools has failed. Statistics are used to show managers, ED, ADM the usefulness of tools and outreach efforts.

**Additional Context**
City of use = where they are using the tool
Is there another tool available that is not Google Analytics?

**Comment by acatchpole** [comment]
highlights of my understandings from email convo with SO:
 - Google Analytics(GA) collected the necessary data.
 - Constant updates to GA made it difficult to maintain a working configuration.
 - SO curious why similar queries often gave different results (need to explain how GA often shows results from a sample)
 - SO is open to a paid alternative if a more suitable alternative can be identified.

**Comment by acatchpole** [comment]
As discussed, this ticket breaks down into 2 issues:

   1. Accessing existing Google Analytics (GA) data for 2023
   2. Looking into current tool options for future use

Findings:

2023 Data: 
- While GA tags are present in both NMP and ARM, the GA account in use is not set up to collect the data from NMP. Only data from ARM is collected and present. The switch from Universal Analytics (UA) to GA4 occurred July 01, 2023. Data before then is pretty good, but after that it relies on some auto-created resources which don't seem to be capturing everything. Also, data collected under UA will become permanently unavailable on July 01, 2024.
- Data can only be exported from report views. So, in order to get what is needed, ***will need to confer with SO to formulate reports for relevant metrics (date ranges, etc.)***

Tool Options:  (please forgive my table formatting. I copied from MS Word...)

Tool | Pros | Cons
-- | -- | --
Google   Analytics (GA4)       https://analytics.google.com/ | - Already in use   - Provides the   necessary data   - Discussion that   indicates it is likely OK privacy-wise ( https://teams.microsoft.com/l/message/19:d2f234de0ca141a1a5e9bd8ff865ac04@thread.tacv2/1695052631194?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&groupId=7101288a-8406-458b-931d-b9e67d67133d&parentMessageId=1695052631194&teamName=Technology%20Innovation%20Forum%20(TIF)&channelName=General&createdTime=1695052631194   )   ·       Free | ·       Some work (both dev   and SO) needs to be done to get everything working under new version   ·       Future updates   could break things again and need further work   ·       Sampling can occur   on some reports (inaccurate/inconsistent numbers)   ·       Has retention   limits on user data (data can expire and be deleted)
Matomo       https://matomo.org/       https://github.com/BCDevOps/matomo-openshift | ·       Open Source   ·       Free when   self-hosted (which it would be)   ·       No sampling   ·       We own/store the   data (won’t expire)   ·       We would be in   control if/when to implement upgrades/updates   ·       In use by other BCGov   teams | ·       Implementing this   will take some time (unsure where it might fall among current priorities)   ·       Implementation of   new tool is less simple than using existing tool (GA4)   ·       Will require SO to   become familiar with new tool   ·       Process for making   sure tool remains up-to-date/secure becomes manual
GDX   (Snowplow) | ·       In use by BCGov | ·       Expensive   ·       Requires   third-party to create reports
MS   Clarity       https://clarity.microsoft.com/ | ·       Free Open Source   ·       Privacy friendly | ·       New tool   ·       Focused mainly on   user behaviour   ·       Probably more   features than necessary

The best options appear to me to be remaining with GA or switching to Matomo. As both choices have their downsides, ***further discussion with SO will be needed to decide what avenue to pursue.***

**Comment by acatchpole** [comment]
SO agreed that utilizing the existing option (Google Analytics) was the prudent approach currently. The work to be done to make sure that it is working will be done in this ticket -> https://github.com/bcgov/agri-nmp/issues/640
