### ISSUE TITLE
Determining Database structure for Liquid Fertigation

### ISSUE THREAD

**Issue by Keegnan** [bcgov/agri-nmp#652]
**Describe the task**
- Reviewing what is tracked at the database level
- Do a first slice to know how much we can hard code and how much we need to rely on the database
- Diagramming and documenting for database planning
- Review the mocks and plan out the table to understand what we need
- Create a diagram of the database

**Purpose**
To understand the flow and process of the database structure.

**Acceptance Criteria**
- [x] Diagram is created of the database
- [] We confirm whether we are doing a first slice that is "quick and dirty"
- [] Include a diagram what is hardcoded and what isn't 

**Additional context**
- [x] Make database diagram for MNP as there is none
- What does the database look like to support fertigation

**Comment by lunamoonmoon** [comment]
From DBeaver this is an ERD for the NMP application. I also saved this to the NMP teams channel.
![Image](https://github.com/user-attachments/assets/0e4d1b42-a345-4c58-a5b4-507beaa17829)

**Comment by lunamoonmoon** [comment]
- We can use FertilizerUnits table which is already in db for conversions then hardcode the rest for now.

Eventual draft of Fertigation tables
![Image](https://github.com/user-attachments/assets/3c7c7d90-3f31-4d2c-b136-b0d6464332aa)
only difference from Fertilizer table row names are possible sharing of FertilizerUnits table and renaming DryLiquid > LiquidSolid (and different row values)
![Image](https://github.com/user-attachments/assets/54662a6b-fa02-4723-ad4e-78c64c2ebc87)

**Comment by lunamoonmoon** [comment]
Hardcoded fertigation data:

[fertigationData.json](https://github.com/user-attachments/files/16664078/fertigationData.json)

**Comment by acatchpole** [comment]
wip : updated

[fertigationData.json](https://github.com/user-attachments/files/16667010/fertigationData.json)

- added fields so is 1-to-1 for the static data file
- began adding liquidFetilizerDensities

need to add L/ac to LiquidMaterialApplicationUsGallonsPerAcreRateConversions
need to add Litre to LiquidMaterialsConversionFactors
maybe? need to add FertigationNutrientCalculator to MiniApps or SubMenu (unsure what tables are for)

**Comment by acatchpole** [comment]
[fertigationData.json](https://github.com/user-attachments/files/16683258/fertigationData.json)

This file includes all the new values to support fertigation. This includes additions to the following tables:
 - fertilizers
 - liquidFetilizerDensities
 - LiquidMaterialApplicationUsGallonsPerAcreRateConversions
 - LiquidMaterialsConversionFactors

The data is formatted such that the new values could be copy-pasted directly into a new Static Data file.

However, also included are the existing values from these tables that Fertigation will use. This file could be used as a quick-and-dirty data source for Fertigation work while a more robust database solution is formulated.

### Database implementation:
There are several strategies for adding this data into the existing tables, but all will require refactoring existing code. This is due to the fact that we are adding new fertilizers to support fertigation. But as well, some existing fertilizers will also be options for fertigation. This means there is no simple existing way to differentiate fertilizers for fertigation from the existing dry and liquid fertilizer selectors.

#### Strategies (in no order of preference):
 1. Do not add data to the database and utilize the hardcoded values in fertigationData.json as the data source. No refactoring of existing code required, but not a good long term solution. Although, there is nothing stopping us from doing this to start, and then refactoring to utilize the database later down the line. The data file is even structured like the database to make conversion easier.
 2. Add the new fertilizers to the ```Fertilizers``` table, along with a new column ```ApplicationMethod```. This field would accept multiple (an array) of values that could include something like ['dry','liquid','fertigation'] in whatever combination. This would require refactoring existing fertilizer selectors to NOT include the fertilizers that only have fertigation.
 3. The DryLiquid column could be refactored to the above. This would reduce duplication of data, but may have unintended side effects.
 4. A new related table is made called ApplicationMethod (or something) that has many-to-one relations to the fertilizers. This functions similarly to adding the new column, but doesn't require modification to the existing table structure.
