### ISSUE TITLE
renew NMP Cert

### ISSUE THREAD

**Issue by jakemorr** [bcgov/agri-nmp#701]
**Describe the task**
NMP's cert is due to expire October 10th, we need to renew it and have a new cert in place before then. 

**Purpose**
maintain the security of the application and not degrade the image of the app with its users.

**Acceptance Criteria**
- [x] NMP has a new Cert

**Additional context**
- Former Susteam Dev has done this work previously
- Documentation: https://apps.nrs.gov.bc.ca/int/confluence/display/SUSTEAM/Entrust+Cert+Creation
- NMP SO can provide financial coding when it is required

- We could a temporary lets encrypt cert while we wait from any information from NRIDS

 
**The basic steps to renew are:**
 - Acquiring new certificates and going through the [renewal process](https://apps.nrs.gov.bc.ca/int/confluence/display/DEVGUILD/SSL+Certificates) requires a developer to generate and install the certificate.
- Developer generates cert
- Developer or Product Owner creates JIRA ticket with the cert’s tracking ID
- Infrastructure order the cert through iStore

**Comment by dallascrichmond** [comment]
- In the process of getting a new cert from Entrust, but will take roughly a week.
- In the meantime we used Let's Encrypt and Certbot to generate a new Cert that will last until Feb 2025
- Link to Certbot documentation: https://github.com/BCDevOps/certbot/blob/master/docker/README.md
- Future tips if someone needs to use Let's encrypt again: Set "CERTBOT_SERVER" to "https://acme-v02.api.letsencrypt.org/directory" and ensure "CERTBOT_DRY_RUN" is set to "false" in order to patch cert to route.

**Comment by Keegnan** [comment]
Let's Encrypt is in place. Waiting for Entrust. Moved to blocked for now.

**Comment by dallascrichmond** [comment]
![Image](https://github.com/user-attachments/assets/d8613a9d-4281-43c1-b0fc-f2e856419251)
The new Entrust cert has been updated and is good until November 10th 2025.
